# permissions for end users to view appdeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appdeployment-viewer-role
rules:
- apiGroups:
  - deploy.semtexzv.com
  resources:
  - appdeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - deploy.semtexzv.com
  resources:
  - appdeployments/status
  verbs:
  - get
