
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - deploy.semtexzv.com
  resources:
  - appdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deploy.semtexzv.com
  resources:
  - appdeployments/status
  verbs:
  - get
  - patch
  - update
